// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAHoTTmGNa_bpcZxJPJ-6doRsIssmZB6As',
    appId: '1:886755733560:web:c0ba11beb77169fbc076cd',
    messagingSenderId: '886755733560',
    projectId: 'masterm-eac66',
    authDomain: 'masterm-eac66.firebaseapp.com',
    storageBucket: 'masterm-eac66.firebasestorage.app',
    measurementId: 'G-MCBKMJ18CQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB5nb9J8u302V8KJuS8IvUmaj3PMMZcdtI',
    appId: '1:886755733560:android:c007615920200f1cc076cd',
    messagingSenderId: '886755733560',
    projectId: 'masterm-eac66',
    storageBucket: 'masterm-eac66.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA5ovAijfRbaJw2_80iSGpAdfmb84U6CbY',
    appId: '1:886755733560:ios:1c74ac8acd82ae01c076cd',
    messagingSenderId: '886755733560',
    projectId: 'masterm-eac66',
    storageBucket: 'masterm-eac66.firebasestorage.app',
    iosClientId: '886755733560-6m80ghsiuqmnljpk3hmgak9e808mtd1j.apps.googleusercontent.com',
    iosBundleId: 'com.example.moviemaster',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA5ovAijfRbaJw2_80iSGpAdfmb84U6CbY',
    appId: '1:886755733560:ios:1c74ac8acd82ae01c076cd',
    messagingSenderId: '886755733560',
    projectId: 'masterm-eac66',
    storageBucket: 'masterm-eac66.firebasestorage.app',
    iosClientId: '886755733560-6m80ghsiuqmnljpk3hmgak9e808mtd1j.apps.googleusercontent.com',
    iosBundleId: 'com.example.moviemaster',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAHoTTmGNa_bpcZxJPJ-6doRsIssmZB6As',
    appId: '1:886755733560:web:3131ecd59944dad6c076cd',
    messagingSenderId: '886755733560',
    projectId: 'masterm-eac66',
    authDomain: 'masterm-eac66.firebaseapp.com',
    storageBucket: 'masterm-eac66.firebasestorage.app',
    measurementId: 'G-NHN5DLGF7M',
  );
}
